### ISSUE TITLE
Work in "javaless" environments?

### ISSUE THREAD

**Issue by johnmakridis** [nikku/node-xsd-schema-validator#25]
Hi, 

Thank you for this great package, it works as well as expected in my dev environment on my computer, unfortunately I can't use it in production since it requires the Java SDK.

I'm using Google's App Engine with Node.js environment for hosting and I can't deploy the application on App Engine since it cannot find/install the Java SDK, it runs a simple nodejs instance, SDKs cannot be installed (I think).

Is there any plan to remove/replace Java in order to be able to install xsd-schema-validator in "javaless" environments?

**Comment by nikku** [comment]
Hi @johnmakridis.

The goal of this library is to be feature complete regarding XSD validation, rather than easy to consume in all NodeJS environments. As [stated in the readme](https://github.com/nikku/node-xsd-schema-validator#why) we use Java because it bundles a full fledged XSD validator. 

There does not exist any alterative that satisfies my requrement on XSD validation completeness, hence this library and the way it works, under the hood. So no, there is no plan to work in a "javaless" environment. 

If you however have input how we can do without Java, please send it. I'm happy to improve this library as long as the feature completeness is given.
